### PR TITLE
Add typescript declaration file.

### PR DESCRIPTION
**Pull request by raineorshine**
This PR will resolve type definitions for xhtml-purifier in projects that use typescript. No additional configuration needed.

### CODE REVIEW

**Comment by cstigler** [comment]
Thanks Raine!

**Comment by raineorshine** [comment]
Hi! Could we get a release?

**Comment by cstigler** [comment]
@raineorshine just published to npm as version 0.4.1

Also, just a heads-up that we haven't actually been using this code since 2016. I'm happy to bump versions and merge simple PRs like this, but if you ever want to make more significant changes, you'll probably want to fork (or I'm happy to make you a maintainer on this repo).

**Comment by raineorshine** [comment]
Thanks! I'm not planning any modifications, but I'll let you know if that changes. Happy to help maintain, but it doesn't look there is much activity field so probably not a problem :).

**Pull request merged**
